### ISSUE TITLE
Allow using global data alongside per-file front matter

### ISSUE THREAD

**Issue by rask** [shinnn/gulp-front-matter#12]
Would it be possible to introduce a config option for importing a generic global configuration file? Something like the following:

```yaml
# global.yaml
hello: world
foo: bar
```

With a file called `index.md`

```
---
title: Asdf
---

Hello world
```

Then in `gulpfile.js`

```js
var fm = require('gulp-front-matter');

gulp.task('compile', function ()
{
    gulp.src('*.md')
        .pipe(fm({ property: 'data', import: 'global.yaml' }))
        .pipe(...)
});
```

Then the `fm` property `data` would contain things as if the Markdown frontmatter had contained

```
---
title: "Asdf"
hello: "world"
foo: "bar"
---
```

Or should/could I combine some other Gulp plugin to achieve this?

**Comment by shinnn** [comment]
> Would it be possible to introduce a config option for importing a generic global configuration file? 

No. We all should obey [gulp plugin guidelines](https://github.com/gulpjs/gulp/blob/5585720cbfa927f041602088d27b551659916e88/docs/writing-a-plugin/guidelines.md) — only do one thing, and do it well.

> should/could I combine some other Gulp plugin to achieve this?

Yes.

**Comment by rask** [comment]
I see. Will have to find out whether something exists already or then get my hands dirty and create something myself. Thanks! :)

**Comment by rask** [comment]
Resolved this by creating a new Gulp plugin which complements gulp-front-matter and gulp-wrap: https://github.com/rask/gulp-yaml-data
