### ISSUE TITLE
@@include routine not working if followed by 1 or several white space

### ISSUE THREAD

**Issue by tevla** [shinnn/gulp-front-matter#14]
If you include an html file using the directive @@include like this
`<!-- @@include ./path/to/file/file.html -->`

and add one or several whitespace at the end of the line
the include directive does not work anymore.

**Comment by shinnn** [comment]
This is not a gulp-front-matter issue but a bug of [the underlying front matter parser](https://github.com/shinnn/gulp-front-matter/blob/22529a77690e1d30cebffeda37f237cafc028883/package.json#L36).
